### PR TITLE
Fixes "Negative Time" issue

### LINKED ISSUE #410: "[warn] Negative time" with sbt 1.4
## steps

A reproducer would be https://github.com/Sciss/Mellite/releases/tag/v3.2.1 - if you clone the repository and check out tag v3.2.1, running sbt +mellite-app/clean +mellite-app/update +mellite-app/test mellite-app/assembly displays the warnings, at least on my computer.

## problem

Since I use sbt 1.4.x, when running assembly, it fills my screen with

```
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
[warn] Negative time
```
(although technically it still seems to succeed)

### PR DESCRIPTION
**Pull request by eed3si9n**
sbt 1.4.0 started wiping the timestamp in the JAR file to 1970-01-01
even though some file system including the DOS timestamp used by ZIP
files are unable to handle file stamp before 1980.
Until this was fixed in sbt 1.4.8, we now have JAR files out in the wild
with 1970-01-01 timestamp.

On the other side, JDK 11 started adding stricter check on this and
started throwing exception "Negative Time" when it thinks the timestamp
is about to be set to something below 1970-01-01.
Maybe due to the timezone 1970-01-01 is actually interpreted to be
1969-12-31 or something. I'm not sure.
But basically the fix is to use some other timestamp when it's before
1980 and that should be ok with JDK 11's 1970-01-01 check.

Fixes #410

### CODE REVIEW

File: src/main/scala/sbtassembly/AssemblyUtils.scala [hunk 1]
```diff
@@ -68,8 +68,14 @@ object AssemblyUtils {
...
               }
             }
-            if(preserveLastModified)
-              target.setLastModified(entry.getTime)
+
+            if (preserveLastModified) {
+              val t: Long = entry.getTime
+              val EPOCH_1980_01_01 = 315532800000L
+              val EPOCH_2010_01_01 = 1262304000000L
+              if (t > EPOCH_1980_01_01) target.setLastModified(t)
```
Comment (polarker) [inline src/main/scala/sbtassembly/AssemblyUtils.scala:76]: is it better to go with `t >= EPOCH_1980_01_01` ?

Comment (eed3si9n) [reply src/main/scala/sbtassembly/AssemblyUtils.scala:76]: Actually there are many edge cases around 1980-01-01 like UTC vs local and https://bugs.openjdk.java.net/browse/JDK-8246129, it might just be safer to pick more later dates.
