### PR TITLE
Fix broken shading on Windows.

### LINKED ISSUE #172: shading messes up test in assembly
I just tried the new shading functionality.  Very promising!  Unfortunately, it causes test in assembly to fail with ClassNotFoundExceptions.   For example, see my commits in this PR:

https://github.com/spark-jobserver/spark-jobserver/pull/275

If you roll back the last commit to disable test in assembly, and run "job-server/test", you will find something like this:

```
java.lang.NoClassDefFoundError: sjs/shapeless/PrependAux$
```

### PR DESCRIPTION
**Pull request by YuvalItzchakov**
Attempting to use the shading functionality on Windows results in files being deleted from the uber JAR as a result of a naming mismatch of one of the `JarJar` processors called `MisplacedClassProcessor`.

Internally, `MisplacedClassProcessor.java` utilizes `org.objectweb.asm.ClassReader.getClassName` which replaces any '.' on the class name with '/' regardless of the underlying OS. This is documented:

> Returns the internal name of the class corresponding to this object or array type. The internal name of a class is its fully qualified name (as returned by Class.getName(), **where '.' are replaced by '/'.** This method should only be used for an object or array type.

All windows class names get translated using '\' instead of '.'. This causes `assemblyShadeRules` to *mismatch all classes*, causing them to be removed from the uber JAR.

This fix makes sure the class name uses '/' instead, for all class names regardless of the OS.

### CODE REVIEW

File: src/main/scala/sbtassembly/Shader.scala [hunk 1]
```diff
@@ -81,7 +81,16 @@ private[sbtassembly] object Shader {
...
+
+    /*
+    jarjar MisplacedClassProcessor class transforms byte[] to a class using org.objectweb.asm.ClassReader.getClassName
+    which always translates class names containing '.' into '/', regardless of OS platform.
+    We need to transform any windows file paths in order for jarjar to match them properly and not omit them.
+     */
+//    val files = AssemblyUtils.getMappings(dir, Set())
+
+    val files = AssemblyUtils.getMappings(dir, Set()).map(f =>
+      if (f._2.contains('\\')) (f._1, f._2.replace('\\', '/')) else f)
```
Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: What do you think about using `PathList` that's doing something similar in here? - https://github.com/sbt/sbt-assembly/blob/74938af540cd64c588210851e913f64bf2800801/src/main/scala/sbtassembly/Assembly.scala#L303-L310

Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: Would you want me to add an additional method to `PathList`? Or use the separated list to concat the path with a `/`?

Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: Yea. I was thinking the latter, like

```scala
val PathList(xs) = f._2
xs.mkString("/")
```

Not sure if it work but at least you'd then have backslash handling in one spot.

File: src/main/scala/sbtassembly/Shader.scala [hunk 2]
```diff
@@ -81,7 +81,16 @@ private[sbtassembly] object Shader {
...
 
     val proc = JJProcessor(jjrules, verbose = level == Level.Debug, true)
-    val files = AssemblyUtils.getMappings(dir, Set())
+
+    /*
+    jarjar MisplacedClassProcessor class transforms byte[] to a class using org.objectweb.asm.ClassReader.getClassName
+    which always translates class names containing '.' into '/', regardless of OS platform.
+    We need to transform any windows file paths in order for jarjar to match them properly and not omit them.
+     */
+//    val files = AssemblyUtils.getMappings(dir, Set())
```
Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: This line should be removed.

File: src/main/scala/sbtassembly/Shader.scala (hunk 1 above)
Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: Problem is that if the string is on a Windows path, it'll currently throw a `MatchError`:

```
scala> val PathList(xs) = "com\\clicktale\\ai"
scala.MatchError: com\clicktale\ai (of class java.lang.String)
  ... 33 elided

scala>
```

Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: On Windows, or on Mac? because it's using `System.getProperty("file.separator")`.

Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: Windows.

Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: Hmm.. `PathList` is trying to split by `\\` double backslash.

Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: Never mind on using `PathList` then.

File: src/main/scala/sbtassembly/Shader.scala (hunk 2 above)
Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: Deleted the commented line. Forgot there while testing both versions :)

**Comment by eed3si9n** [comment]
LGTM pending Travis.

**Comment by YuvalItzchakov** [comment]
Is there a reason travis is taking so long?

**Comment by eed3si9n** [comment]
It got queued behind sbt/sbt, which takes really long time to validate PRs. Sorry.

**Comment by eed3si9n** [comment]
First one passed, so I can merge this as is.

**Comment by YuvalItzchakov** [comment]
Is there a planned release coming up soon?

**Comment by dragos** [comment]
Fantastic, thanks @YuvalItzchakov for fixing this!

File: src/main/scala/sbtassembly/Shader.scala [hunk 3]
```diff
@@ -81,7 +81,14 @@ private[sbtassembly] object Shader {
...
     val proc = JJProcessor(jjrules, verbose = level == Level.Debug, true)
-    val files = AssemblyUtils.getMappings(dir, Set())
+
+    /*
+    jarjar MisplacedClassProcessor class transforms byte[] to a class using org.objectweb.asm.ClassReader.getClassName
+    which always translates class names containing '.' into '/', regardless of OS platform.
+    We need to transform any windows file paths in order for jarjar to match them properly and not omit them.
+     */
+    val files = AssemblyUtils.getMappings(dir, Set()).map(f =>
+      if (f._2.contains('\\')) (f._1, f._2.replace('\\', '/')) else f)
```
Comment (dragos) [inline src/main/scala/sbtassembly/Shader.scala]: Shouldn't this be done only on Windows? Not sure if files are likely to contain `\` on Linux, though... probably not a big deal.

Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: There's a discussion here - https://github.com/sbt/sbt-assembly/pull/206#discussion_r58748125
I might try fixing it.

Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: It will only be replaced in case there is a windows path.

Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: Ok, During investigation of the issue, I see that shading rules only execute if this `if` clause falls through:

// If the jar name path does not exist, or is not for this jar, unzip the jar
`if (!ao.cacheUnzip || !jarNamePath.exists || IO.read(jarNamePath) != jar.data.getCanonicalPath)`

Otherwise, it won't fall through. This means that if I have the JAR i'm trying to Shade on the target assemblyOption, it won't shade the directory and put it inside the JAR. I'm not sure if this is expected behavior, it seems weird. Should there be an added check if the said JAR is on the shadeRules list?

Comment (eed3si9n) [inline src/main/scala/sbtassembly/Shader.scala]: Maybe the added check should be that the shadeRules have changed since the last time you called `assembly`? If you can cache unzip that's usually a good thing.

Comment (YuvalItzchakov) [inline src/main/scala/sbtassembly/Shader.scala]: So this is actually a result of the caching, I see. Is there any field that signals mutation of a rule in the build.sbt?
